export const en = {
    pendingRequests: "Pending Requests",
    filterByType: "Filter by Type:",
    filterByStatus: "Filter by Status:",
    all: "All",
    leave: "Leave",
    travel: "Travel",
    expense: "Expense",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    request: "Request",
    startDate: "Start Date",
    endDate: "End Date",
    reason: "Reason",
    status: "Status",
    submitARequest: "Submit a Request",
    requestType: "Request Type:",
    attachment: "Attachment:",
    department: "Department:",
    submit: "Submit",
    successMessage: "Your request has been submitted successfully.",
    errorMessage: "There was an error submitting your request. Please try again.",
    myRequestsOverview: "My Requests Overview",
  };
  