export const vi = {
    requests: "Danh sách yêu cầu",
    pendingRequests: "Yêu cầu chờ xử lý",
    filterByType: "Lọc theo loại:",
    filterByStatus: "Lọc theo trạng thái:",
    all: "Tất cả",
    leave: "Nghỉ phép",
    travel: "Công tác",
    expense: "Chi phí",
    pending: "Chờ xử lý",
    approved: "Phê duyệt",
    rejected: "Từ chối",
    request: "Yêu cầu",
    startDate: "Ngày bắt đầu",
    endDate: "Ngày kết thúc",
    reason: "Lý do",
    status: "Trạng thái",
    submitARequest: "Gửi yêu cầu",
    requestType: "Loại yêu cầu:",
    attachment: "Tập tin đính kèm:",
    department: "Phòng ban:",
    submit: "Gửi",
    successMessage: "Yêu cầu của bạn đã được gửi thành công.",
    errorMessage: "Đã xảy ra lỗi khi gửi yêu cầu của bạn. Vui lòng thử lại.",
    myRequestsOverview: "Tổng quan về yêu cầu của tôi",
    dashboard: "Tổng quan",
    managerPanel : "Bảng quản lý",
    reports : "Báo cáo"
  };
  